meetings/README.md
for immersive-web/administrivia #35.
=> Added teleconference overview as directory readme in repository

project.md
Might want to just remove this but the link we have now is not current.
=> Update the link for issue details.

F2F-Jun-2019/schedule.md
=> John will cover DOM overlays, not Brandon

modules.md
=> Move XRRay and immersive-ar mode to AR.

meetings/wg/2019-06-11-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-06-18-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes for 2019/Jun/11,18

meetings/wg/2019-06-25-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes 2019/06/25

meetings/wg/2019-07-16-Immersive_Web_Working_Group_Teleconference-agenda.md
=> Add minutes 20190716

meetings/wg/2018-12-11-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-01-08-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-01-22-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-02-05-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-02-19-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-03-05-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-04-02-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-04-16-Immersive_Web_Working_Group_Teleconference-agenda.md, meetings/wg/2019-04-30-Immersive_Web_Working_Group_Teleconference-agenda.md
for existing ones before of which I've started to add right after calls.
=> added links to minutes where missing and/or exists on w3.org scribe

meetings/wg/2019-09-10-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes on 2019/09/10

meetings/wg/2019-10-08-Immersive_Web_Working_Group_Teleconference-agenda.md
This was left over from the agenda generator
=> remove line coming from CG item

meetings/wg/2019-10-08-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes 2019/10/08

meetings/wg/2019-10-22-Immersive_Web_Working_Group_Teleconference-agenda.md
r? @AdaRoseCannon 
cc @NellWaliczek @toji
=> Restructure xr session mode agenda items

meetings/wg/2019-12-03-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added link to 2019/Dec/03 minutes

meetings/wg/2019-12-17-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes 2019/12/17

meetings/wg/2020-06-02-Immersive_Web_Working_Group_Teleconference-agenda.md
Add minutes to 2020-06-02-Immersive_Web_Working_Group_Teleconference-agenda
=> Add minutes to 2020-06-02

meetings/cg/2020-05-19-Immersive_Web_Community_Group_Teleconference-agenda.md, meetings/wg/2020-05-12-Immersive_Web_Working_Group_Teleconference-agenda.md
Closes [Issue #103 ](https://github.com/immersive-web/administrivia/issues/103)
Thanks!
=> Fix minute links

meetings/wg/2020-06-23-Immersive_Web_Working_Group_Teleconference-agenda.md
=> Remove last weeks agenda items

meetings/cg/2020-08-18-Immersive_Web_Community_Group_Teleconference-agenda.md
Update 2020-08-18-Immersive_Web_Community_Group_Teleconference-agenda.md
=> Add minutes 

TPAC-2020/readme.md
I've added an outline for the schedule for TPAC meetings for next week. 
First day we will go over the repos listed in the schedule. If you are the lead(tagged in the calendar), please give us a 5 minute update for the repo:
If you would like to have an unconference session, please suggest a time slot that is open currently by commenting in this PR or reach out through email.
Looking forward to seeing you all next week. 
Thank you!
Aysegul
=> TPAC 2020 schedule

TPAC-2020/readme.md
I'm looking into image tracking, but not face tracking which seems like a separate issue. Clarifying the agenda to avoid confusion.
=> Remove "face tracking" for @klausw topic

TPAC-2020/readme.md
just an idea. 
check html at https://github.com/himorin/immersive-web-administrivia/tree/tpac2020-modifytable/TPAC-2020
=> proposal for simplification of date/time table

TPAC-2020/readme.md
This is the first draft of our schedule based on the requests. Feel free to object and ask for different times.
=> Add Wed-Fri tpac schedule

meetings/README.md
Feel free to suggest or add other todos I might be missing.
=> Update for planning TPAC or f2f README.md

meetings/wg/2020-11-17-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added missing minutes (2020/09/29 was not found on server)

meetings/wg/2021-01-05-Immersive_Web_Working_Group_Teleconference-agenda.md
=> marked as cancelled

README.md, meetings/README.md
adding some for face-to-face, and updates for comments at #181
=> updates for meetings/teleconferences description

TPAC-2022/readme.md
@AdaRoseCannon @cwilso, I couldn't find the joint meeting time in my emails. Could you please fill it in. Let me know if the agenda looks good to you.
Thanks!
=> Add day 1 & 2 agenda

F2F-April-2023/schedule.md
Please feel free to discard this, if already under preparation.
=> added tentative schedule page for 2023/Apr

meetings/wg/2023-02-21-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes 2023/02/21

meetings/wg/2023-02-07-Immersive_Web_Working_Group_Teleconference-agenda.md
=> added minutes to 2023-02-07

meetings/2024/2024-06-11-Immersive_Web_Working_Group_Teleconference-agenda.md
@AdaRoseCannon I've generated minutes from irc log, and pushed to w3.org website. (sorry for taking time to jump into this)
=> added minutes - 2024-06-11

meetings/2024/2024-07-10-Immersive_Web_Community_Group_Teleconference-agenda.md
=> 2024-07-09 call minutes

meetings/2024/2024-10-15-Immersive_Web_Working_Group_Teleconference-agenda.md
minutes cleaned up and fixed link
=> 2024-10-15 minutes link

meetings/2024/2024-10-29-Immersive_Web_Community_Group_Teleconference-agenda.md
=> added minutes line
